// ========================
// Mock Data for TeamFlow PM - Project Management Software
// ========================

import type {
  Task, Project, Sprint, Milestone, TimeEntry,
  PMUser, Automation, AuditLogEntry, CalendarEvent,
  Organization,
} from './types';

// ─── Users ──────────────────────────────────────────────────────────────
export const mockUsers: PMUser[] = [
  { id: 'u-1', name: 'Marie Dupont', email: 'marie@globalcorp.com', avatar: '', role: 'org_admin', status: 'online', organizationId: 'org-1', organizationName: 'Global Corp France', lastActive: new Date().toISOString(), taskCount: 8 },
  { id: 'u-2', name: 'Jean-Pierre Martin', email: 'jp.martin@globalcorp.com', avatar: '', role: 'project_manager', status: 'online', organizationId: 'org-1', organizationName: 'Global Corp France', lastActive: new Date().toISOString(), taskCount: 6 },
  { id: 'u-3', name: 'Sophie Laurent', email: 'sophie.l@globalcorp.com', avatar: '', role: 'member', status: 'away', organizationId: 'org-1', organizationName: 'Global Corp France', lastActive: new Date(Date.now() - 30 * 60000).toISOString(), taskCount: 5 },
  { id: 'u-4', name: 'Patrick Mbeki', email: 'patrick@globalcorp-rdc.com', avatar: '', role: 'org_admin', status: 'online', organizationId: 'org-2', organizationName: 'Global Corp RDC', lastActive: new Date().toISOString(), taskCount: 4 },
  { id: 'u-5', name: 'Aminata Diallo', email: 'aminata@globalcorp-rdc.com', avatar: '', role: 'member', status: 'offline', organizationId: 'org-2', organizationName: 'Global Corp RDC', lastActive: new Date(Date.now() - 2 * 3600000).toISOString(), taskCount: 3 },
  { id: 'u-6', name: 'Lucas Bernard', email: 'lucas@techbrand.com', avatar: '', role: 'project_manager', status: 'busy', organizationId: 'org-3', organizationName: 'TechBrand', lastActive: new Date(Date.now() - 10 * 60000).toISOString(), taskCount: 7 },
  { id: 'u-7', name: 'Claire Moreau', email: 'claire@globalcorp.com', avatar: '', role: 'member', status: 'online', organizationId: 'org-1', organizationName: 'Global Corp France', lastActive: new Date().toISOString(), taskCount: 4 },
  { id: 'u-8', name: 'David Koffi', email: 'david@globalcorp-rdc.com', avatar: '', role: 'viewer', status: 'offline', organizationId: 'org-2', organizationName: 'Global Corp RDC', lastActive: new Date(Date.now() - 24 * 3600000).toISOString(), taskCount: 1 },
];

// ─── Projects ───────────────────────────────────────────────────────────
export const mockProjects: Project[] = [
  {
    id: 'p-1',
    name: 'Refonte Platform',
    description: 'Refonte complète de la plateforme interne avec nouvelle UX/UI',
    icon: '🚀',
    color: '#10b981',
    status: 'active',
    progress: 68,
    memberIds: ['u-1', 'u-2', 'u-3', 'u-7'],
    taskCount: 24,
    completedTasks: 16,
    dueDate: '2025-08-30',
    startDate: '2025-03-01',
    organizationId: 'org-1',
    createdAt: '2025-02-15T10:00:00Z',
    updatedAt: '2025-06-06T14:00:00Z',
  },
  {
    id: 'p-2',
    name: 'App Mobile v2',
    description: 'Deuxième version de l\'application mobile avec mode hors-ligne',
    icon: '📱',
    color: '#f59e0b',
    status: 'active',
    progress: 42,
    memberIds: ['u-2', 'u-3', 'u-5'],
    taskCount: 18,
    completedTasks: 7,
    dueDate: '2025-09-15',
    startDate: '2025-04-01',
    organizationId: 'org-1',
    createdAt: '2025-03-20T09:00:00Z',
    updatedAt: '2025-06-05T16:00:00Z',
  },
  {
    id: 'p-3',
    name: 'Migration Cloud',
    description: 'Migration de l\'infrastructure vers le cloud AWS',
    icon: '☁️',
    color: '#06b6d4',
    status: 'active',
    progress: 55,
    memberIds: ['u-1', 'u-4', 'u-5'],
    taskCount: 15,
    completedTasks: 8,
    dueDate: '2025-07-31',
    startDate: '2025-02-01',
    organizationId: 'org-2',
    createdAt: '2025-01-20T08:00:00Z',
    updatedAt: '2025-06-06T11:00:00Z',
  },
  {
    id: 'p-4',
    name: 'Module Paiement',
    description: 'Intégration du système de paiement multi-devises',
    icon: '💳',
    color: '#ef4444',
    status: 'on_hold',
    progress: 30,
    memberIds: ['u-6', 'u-7'],
    taskCount: 12,
    completedTasks: 3,
    dueDate: '2025-10-30',
    startDate: '2025-05-01',
    organizationId: 'org-3',
    createdAt: '2025-04-15T10:00:00Z',
    updatedAt: '2025-06-04T09:00:00Z',
  },
  {
    id: 'p-5',
    name: 'Portail Client',
    description: 'Portail self-service pour les clients avec suivi de projets',
    icon: '🌐',
    color: '#8b5cf6',
    status: 'active',
    progress: 15,
    memberIds: ['u-2', 'u-6', 'u-7'],
    taskCount: 20,
    completedTasks: 3,
    dueDate: '2025-11-30',
    startDate: '2025-06-01',
    organizationId: 'org-1',
    createdAt: '2025-05-20T14:00:00Z',
    updatedAt: '2025-06-06T10:00:00Z',
  },
  {
    id: 'p-6',
    name: 'Sécurité & Conformité',
    description: 'Mise en conformité RGPD et renforcement de la sécurité',
    icon: '🔒',
    color: '#64748b',
    status: 'completed',
    progress: 100,
    memberIds: ['u-1', 'u-3'],
    taskCount: 10,
    completedTasks: 10,
    dueDate: '2025-05-31',
    startDate: '2025-01-15',
    organizationId: 'org-1',
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2025-05-28T16:00:00Z',
  },
];

// ─── Tasks ──────────────────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Refonte UI Dashboard',
    description: 'Redesign complet du dashboard avec nouveaux composants et chartes graphiques',
    status: 'in_progress',
    priority: 'high',
    projectId: 'p-1',
    sprintId: 'sp-1',
    assigneeId: 'u-3',
    reporterId: 'u-1',
    dueDate: '2025-06-15',
    tags: ['UI', 'dashboard'],
    subtasks: [
      { id: 'st-1', title: 'Maquettes Figma', completed: true },
      { id: 'st-2', title: 'Composants React', completed: true },
      { id: 'st-3', title: 'Intégration données', completed: false },
      { id: 'st-4', title: 'Tests responsive', completed: false },
    ],
    estimatedHours: 24,
    loggedHours: 16,
    milestoneId: 'ms-1',
    organizationId: 'org-1',
    createdAt: '2025-05-20T10:00:00Z',
    updatedAt: '2025-06-06T14:00:00Z',
  },
  {
    id: 'task-2',
    title: 'API endpoints Sprint 4',
    description: 'Développer les endpoints REST pour le sprint 4 incluant CRUD tâches et projets',
    status: 'done',
    priority: 'urgent',
    projectId: 'p-1',
    sprintId: 'sp-1',
    assigneeId: 'u-2',
    reporterId: 'u-1',
    dueDate: '2025-06-10',
    tags: ['API', 'backend'],
    subtasks: [
      { id: 'st-5', title: 'CRUD tâches', completed: true },
      { id: 'st-6', title: 'CRUD projets', completed: true },
      { id: 'st-7', title: 'Tests unitaires', completed: true },
    ],
    estimatedHours: 20,
    loggedHours: 22,
    milestoneId: 'ms-1',
    organizationId: 'org-1',
    createdAt: '2025-05-25T08:00:00Z',
    updatedAt: '2025-06-05T17:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Module hors-ligne iOS',
    description: 'Implémentation du mode hors-ligne pour l\'app iOS avec synchronisation',
    status: 'in_progress',
    priority: 'high',
    projectId: 'p-2',
    sprintId: 'sp-2',
    assigneeId: 'u-2',
    reporterId: 'u-1',
    dueDate: '2025-06-20',
    tags: ['iOS', 'offline'],
    subtasks: [
      { id: 'st-8', title: 'Cache local CoreData', completed: true },
      { id: 'st-9', title: 'Sync conflict resolution', completed: false },
      { id: 'st-10', title: 'UI état offline', completed: false },
    ],
    estimatedHours: 32,
    loggedHours: 14,
    milestoneId: 'ms-2',
    organizationId: 'org-1',
    createdAt: '2025-06-01T09:00:00Z',
    updatedAt: '2025-06-06T11:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Migration base de données',
    description: 'Migrer la base PostgreSQL vers AWS RDS avec zéro downtime',
    status: 'in_progress',
    priority: 'urgent',
    projectId: 'p-3',
    sprintId: 'sp-3',
    assigneeId: 'u-4',
    reporterId: 'u-1',
    dueDate: '2025-06-12',
    tags: ['migration', 'cloud'],
    subtasks: [
      { id: 'st-11', title: 'Schéma migration', completed: true },
      { id: 'st-12', title: 'Data pipeline', completed: true },
      { id: 'st-13', title: 'Validation integrité', completed: false },
      { id: 'st-14', title: 'Switch DNS', completed: false },
    ],
    estimatedHours: 40,
    loggedHours: 28,
    milestoneId: 'ms-3',
    organizationId: 'org-2',
    createdAt: '2025-05-15T10:00:00Z',
    updatedAt: '2025-06-06T09:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Intégration Stripe',
    description: 'Intégrer Stripe pour les paiements multi-devises et abonnements',
    status: 'todo',
    priority: 'high',
    projectId: 'p-4',
    assigneeId: 'u-6',
    reporterId: 'u-1',
    dueDate: '2025-07-15',
    tags: ['paiement', 'Stripe'],
    subtasks: [
      { id: 'st-15', title: 'Setup Stripe account', completed: false },
      { id: 'st-16', title: 'Webhook handlers', completed: false },
      { id: 'st-17', title: 'UI checkout', completed: false },
    ],
    estimatedHours: 28,
    loggedHours: 0,
    organizationId: 'org-3',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2025-06-01T08:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Design system composants',
    description: 'Créer la bibliothèque de composants réutilisables du design system',
    status: 'review',
    priority: 'medium',
    projectId: 'p-1',
    sprintId: 'sp-1',
    assigneeId: 'u-7',
    reporterId: 'u-2',
    dueDate: '2025-06-18',
    tags: ['design-system', 'UI'],
    subtasks: [
      { id: 'st-18', title: 'Buttons & inputs', completed: true },
      { id: 'st-19', title: 'Cards & modals', completed: true },
      { id: 'st-20', title: 'Tables & lists', completed: true },
      { id: 'st-21', title: 'Documentation Storybook', completed: false },
    ],
    estimatedHours: 18,
    loggedHours: 16,
    milestoneId: 'ms-1',
    organizationId: 'org-1',
    createdAt: '2025-05-22T11:00:00Z',
    updatedAt: '2025-06-06T15:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Authentification SSO',
    description: 'Implémenter l\'authentification SSO avec SAML 2.0 pour les clients entreprise',
    status: 'todo',
    priority: 'medium',
    projectId: 'p-5',
    assigneeId: 'u-2',
    reporterId: 'u-1',
    dueDate: '2025-07-30',
    tags: ['auth', 'SSO'],
    subtasks: [
      { id: 'st-22', title: 'Configuration IdP', completed: false },
      { id: 'st-23', title: 'Flux SAML', completed: false },
      { id: 'st-24', title: 'Tests integration', completed: false },
    ],
    estimatedHours: 22,
    loggedHours: 0,
    organizationId: 'org-1',
    createdAt: '2025-06-03T09:00:00Z',
    updatedAt: '2025-06-03T09:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Rapports automatisés',
    description: 'Générer des rapports PDF hebdomadaires automatiquement avec métriques',
    status: 'in_progress',
    priority: 'medium',
    projectId: 'p-5',
    assigneeId: 'u-3',
    reporterId: 'u-2',
    dueDate: '2025-07-20',
    tags: ['rapports', 'automatisation'],
    subtasks: [
      { id: 'st-25', title: 'Template PDF', completed: true },
      { id: 'st-26', title: 'Génération données', completed: false },
      { id: 'st-27', title: 'Envoi email auto', completed: false },
    ],
    estimatedHours: 16,
    loggedHours: 6,
    organizationId: 'org-1',
    createdAt: '2025-06-02T10:00:00Z',
    updatedAt: '2025-06-06T13:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Configuration AWS IAM',
    description: 'Configurer les rôles et politiques IAM pour la migration cloud',
    status: 'done',
    priority: 'high',
    projectId: 'p-3',
    sprintId: 'sp-3',
    assigneeId: 'u-5',
    reporterId: 'u-4',
    dueDate: '2025-06-05',
    tags: ['AWS', 'sécurité'],
    subtasks: [
      { id: 'st-28', title: 'Rôles ECS', completed: true },
      { id: 'st-29', title: 'Policies RDS', completed: true },
      { id: 'st-30', title: 'Audit permissions', completed: true },
    ],
    estimatedHours: 12,
    loggedHours: 10,
    milestoneId: 'ms-3',
    organizationId: 'org-2',
    createdAt: '2025-05-10T08:00:00Z',
    updatedAt: '2025-06-04T17:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Tests E2E Cypress',
    description: 'Écrire les tests end-to-end Cypress pour les flux critiques',
    status: 'todo',
    priority: 'medium',
    projectId: 'p-1',
    sprintId: 'sp-4',
    assigneeId: 'u-3',
    reporterId: 'u-2',
    dueDate: '2025-06-25',
    tags: ['testing', 'E2E'],
    subtasks: [
      { id: 'st-31', title: 'Setup Cypress', completed: false },
      { id: 'st-32', title: 'Flux login', completed: false },
      { id: 'st-33', title: 'Flux création projet', completed: false },
    ],
    estimatedHours: 14,
    loggedHours: 0,
    organizationId: 'org-1',
    createdAt: '2025-06-04T14:00:00Z',
    updatedAt: '2025-06-04T14:00:00Z',
  },
  {
    id: 'task-11',
    title: 'Optimisation performance',
    description: 'Optimiser les temps de chargement et réduire le bundle size de 40%',
    status: 'in_progress',
    priority: 'high',
    projectId: 'p-1',
    sprintId: 'sp-1',
    assigneeId: 'u-1',
    reporterId: 'u-1',
    dueDate: '2025-06-20',
    tags: ['performance', 'optimisation'],
    subtasks: [
      { id: 'st-34', title: 'Audit Lighthouse', completed: true },
      { id: 'st-35', title: 'Code splitting', completed: true },
      { id: 'st-36', title: 'Lazy loading', completed: false },
      { id: 'st-37', title: 'Image optimization', completed: false },
    ],
    estimatedHours: 20,
    loggedHours: 12,
    milestoneId: 'ms-1',
    organizationId: 'org-1',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2025-06-06T12:00:00Z',
  },
  {
    id: 'task-12',
    title: 'Documentation API OpenAPI',
    description: 'Rédiger la documentation OpenAPI/Swagger pour tous les endpoints',
    status: 'review',
    priority: 'low',
    projectId: 'p-1',
    sprintId: 'sp-1',
    assigneeId: 'u-7',
    reporterId: 'u-2',
    dueDate: '2025-06-22',
    tags: ['documentation', 'API'],
    subtasks: [
      { id: 'st-38', title: 'Endpoints auth', completed: true },
      { id: 'st-39', title: 'Endpoints CRUD', completed: true },
      { id: 'st-40', title: 'Exemples requests', completed: false },
    ],
    estimatedHours: 10,
    loggedHours: 8,
    organizationId: 'org-1',
    createdAt: '2025-05-28T11:00:00Z',
    updatedAt: '2025-06-06T10:00:00Z',
  },
  {
    id: 'task-13',
    title: 'Notification push Android',
    description: 'Implémenter les notifications push FCM pour l\'app Android',
    status: 'todo',
    priority: 'medium',
    projectId: 'p-2',
    assigneeId: 'u-5',
    reporterId: 'u-2',
    dueDate: '2025-07-10',
    tags: ['Android', 'notifications'],
    subtasks: [
      { id: 'st-41', title: 'Setup FCM', completed: false },
      { id: 'st-42', title: 'Background handlers', completed: false },
    ],
    estimatedHours: 12,
    loggedHours: 0,
    organizationId: 'org-1',
    createdAt: '2025-06-05T08:00:00Z',
    updatedAt: '2025-06-05T08:00:00Z',
  },
  {
    id: 'task-14',
    title: 'Audit sécurité OWASP',
    description: 'Réaliser un audit de sécurité selon les guidelines OWASP Top 10',
    status: 'done',
    priority: 'urgent',
    projectId: 'p-6',
    assigneeId: 'u-1',
    reporterId: 'u-1',
    dueDate: '2025-05-20',
    tags: ['sécurité', 'audit'],
    subtasks: [
      { id: 'st-43', title: 'Scan vulnerabilities', completed: true },
      { id: 'st-44', title: 'Rapport findings', completed: true },
      { id: 'st-45', title: 'Remediation plan', completed: true },
    ],
    estimatedHours: 30,
    loggedHours: 26,
    milestoneId: 'ms-5',
    organizationId: 'org-1',
    createdAt: '2025-04-01T09:00:00Z',
    updatedAt: '2025-05-18T16:00:00Z',
  },
  {
    id: 'task-15',
    title: 'Dashboard analytics client',
    description: 'Créer le dashboard analytics côté client avec graphiques temps réel',
    status: 'in_progress',
    priority: 'high',
    projectId: 'p-5',
    assigneeId: 'u-6',
    reporterId: 'u-2',
    dueDate: '2025-08-01',
    tags: ['analytics', 'dashboard'],
    subtasks: [
      { id: 'st-46', title: 'Charts library setup', completed: true },
      { id: 'st-47', title: 'KPI widgets', completed: true },
      { id: 'st-48', title: 'Real-time updates', completed: false },
      { id: 'st-49', title: 'Export PDF', completed: false },
    ],
    estimatedHours: 26,
    loggedHours: 14,
    milestoneId: 'ms-6',
    organizationId: 'org-1',
    createdAt: '2025-06-01T14:00:00Z',
    updatedAt: '2025-06-06T16:00:00Z',
  },
  {
    id: 'task-16',
    title: 'Pipeline CI/CD',
    description: 'Mettre en place le pipeline CI/CD avec GitHub Actions pour le déploiement continu',
    status: 'todo',
    priority: 'medium',
    projectId: 'p-3',
    assigneeId: 'u-5',
    reporterId: 'u-4',
    dueDate: '2025-07-05',
    tags: ['DevOps', 'CI/CD'],
    subtasks: [
      { id: 'st-50', title: 'GitHub Actions workflows', completed: false },
      { id: 'st-51', title: 'Docker images', completed: false },
      { id: 'st-52', title: 'Deploy staging', completed: false },
    ],
    estimatedHours: 18,
    loggedHours: 0,
    organizationId: 'org-2',
    createdAt: '2025-06-03T10:00:00Z',
    updatedAt: '2025-06-03T10:00:00Z',
  },
];

// ─── Sprints ────────────────────────────────────────────────────────────
export const mockSprints: Sprint[] = [
  {
    id: 'sp-1',
    name: 'Sprint 4 - UI & API',
    projectId: 'p-1',
    status: 'active',
    startDate: '2025-06-02',
    endDate: '2025-06-20',
    goal: 'Finaliser la refonte UI du dashboard et les endpoints API du sprint 4',
    taskIds: ['task-1', 'task-2', 'task-6', 'task-11', 'task-12'],
    velocity: 34,
    organizationId: 'org-1',
    createdAt: '2025-05-28T10:00:00Z',
  },
  {
    id: 'sp-2',
    name: 'Sprint 3 - Mobile Offline',
    projectId: 'p-2',
    status: 'active',
    startDate: '2025-06-01',
    endDate: '2025-06-21',
    goal: 'Implémenter le mode hors-ligne sur iOS et les notifications push',
    taskIds: ['task-3', 'task-13'],
    velocity: 28,
    organizationId: 'org-1',
    createdAt: '2025-05-25T09:00:00Z',
  },
  {
    id: 'sp-3',
    name: 'Sprint 2 - Cloud Migration',
    projectId: 'p-3',
    status: 'active',
    startDate: '2025-05-26',
    endDate: '2025-06-14',
    goal: 'Migrer la base de données et configurer l\'infrastructure AWS',
    taskIds: ['task-4', 'task-9'],
    velocity: 22,
    organizationId: 'org-2',
    createdAt: '2025-05-20T08:00:00Z',
  },
  {
    id: 'sp-4',
    name: 'Sprint 5 - Quality & Docs',
    projectId: 'p-1',
    status: 'planning',
    startDate: '2025-06-23',
    endDate: '2025-07-11',
    goal: 'Tests E2E, documentation et optimisations finales',
    taskIds: ['task-10'],
    velocity: 0,
    organizationId: 'org-1',
    createdAt: '2025-06-06T10:00:00Z',
  },
  {
    id: 'sp-5',
    name: 'Sprint 1 - Foundation',
    projectId: 'p-1',
    status: 'completed',
    startDate: '2025-03-03',
    endDate: '2025-03-21',
    goal: 'Mise en place de l\'architecture et des fondations techniques',
    taskIds: [],
    velocity: 40,
    organizationId: 'org-1',
    createdAt: '2025-02-28T10:00:00Z',
  },
  {
    id: 'sp-6',
    name: 'Sprint 2 - Core Features',
    projectId: 'p-1',
    status: 'completed',
    startDate: '2025-03-24',
    endDate: '2025-04-11',
    goal: 'Développement des fonctionnalités principales du projet',
    taskIds: [],
    velocity: 36,
    organizationId: 'org-1',
    createdAt: '2025-03-21T10:00:00Z',
  },
];

// ─── Milestones ─────────────────────────────────────────────────────────
export const mockMilestones: Milestone[] = [
  {
    id: 'ms-1',
    title: 'Alpha Release',
    description: 'Première version alpha avec fonctionnalités principales',
    projectId: 'p-1',
    dueDate: '2025-06-30',
    status: 'in_progress',
    taskIds: ['task-1', 'task-2', 'task-6', 'task-11'],
    color: '#10b981',
    organizationId: 'org-1',
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'ms-2',
    title: 'Beta Mobile',
    description: 'Version beta de l\'application mobile avec mode hors-ligne',
    projectId: 'p-2',
    dueDate: '2025-07-31',
    status: 'upcoming',
    taskIds: ['task-3', 'task-13'],
    color: '#f59e0b',
    organizationId: 'org-1',
    createdAt: '2025-04-01T09:00:00Z',
  },
  {
    id: 'ms-3',
    title: 'Cloud Go-Live',
    description: 'Migration cloud terminée et application live sur AWS',
    projectId: 'p-3',
    dueDate: '2025-07-15',
    status: 'in_progress',
    taskIds: ['task-4', 'task-9'],
    color: '#06b6d4',
    organizationId: 'org-2',
    createdAt: '2025-01-20T08:00:00Z',
  },
  {
    id: 'ms-4',
    title: 'Paiement v1',
    description: 'Première version du module de paiement multi-devises',
    projectId: 'p-4',
    dueDate: '2025-08-30',
    status: 'upcoming',
    taskIds: ['task-5'],
    color: '#ef4444',
    organizationId: 'org-3',
    createdAt: '2025-04-15T10:00:00Z',
  },
  {
    id: 'ms-5',
    title: 'RGPD Compliance',
    description: 'Mise en conformité RGPD complète avec documentation',
    projectId: 'p-6',
    dueDate: '2025-05-31',
    status: 'completed',
    taskIds: ['task-14'],
    color: '#64748b',
    organizationId: 'org-1',
    completedAt: '2025-05-28T16:00:00Z',
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    id: 'ms-6',
    title: 'Client Portal MVP',
    description: 'Version MVP du portail client avec analytics basiques',
    projectId: 'p-5',
    dueDate: '2025-09-30',
    status: 'upcoming',
    taskIds: ['task-7', 'task-8', 'task-15'],
    color: '#8b5cf6',
    organizationId: 'org-1',
    createdAt: '2025-05-20T14:00:00Z',
  },
  {
    id: 'ms-7',
    title: 'Production Release',
    description: 'Mise en production de la plateforme refaite',
    projectId: 'p-1',
    dueDate: '2025-08-30',
    status: 'upcoming',
    taskIds: [],
    color: '#10b981',
    organizationId: 'org-1',
    createdAt: '2025-02-15T10:00:00Z',
  },
  {
    id: 'ms-8',
    title: 'Infrastructure Setup',
    description: 'Infrastructure cloud AWS opérationnelle',
    projectId: 'p-3',
    dueDate: '2025-05-15',
    status: 'overdue',
    taskIds: ['task-9'],
    color: '#06b6d4',
    organizationId: 'org-2',
    createdAt: '2025-01-20T08:00:00Z',
  },
];

// ─── Time Entries ───────────────────────────────────────────────────────
export const mockTimeEntries: TimeEntry[] = [
  { id: 'te-1', taskId: 'task-1', projectId: 'p-1', userId: 'u-3', date: '2025-06-06', hours: 4, description: 'Travail sur les composants du dashboard', billable: true, createdAt: '2025-06-06T18:00:00Z' },
  { id: 'te-2', taskId: 'task-2', projectId: 'p-1', userId: 'u-2', date: '2025-06-06', hours: 3, description: 'Développement endpoints API', billable: true, createdAt: '2025-06-06T17:00:00Z' },
  { id: 'te-3', taskId: 'task-3', projectId: 'p-2', userId: 'u-2', date: '2025-06-06', hours: 5, description: 'Implémentation mode hors-ligne', billable: true, createdAt: '2025-06-06T18:00:00Z' },
  { id: 'te-4', taskId: 'task-4', projectId: 'p-3', userId: 'u-4', date: '2025-06-06', hours: 6, description: 'Migration données PostgreSQL', billable: true, createdAt: '2025-06-06T19:00:00Z' },
  { id: 'te-5', taskId: 'task-1', projectId: 'p-1', userId: 'u-3', date: '2025-06-05', hours: 6, description: 'Intégration composants React', billable: true, createdAt: '2025-06-05T18:00:00Z' },
  { id: 'te-6', taskId: 'task-11', projectId: 'p-1', userId: 'u-1', date: '2025-06-06', hours: 4, description: 'Code splitting et optimisation', billable: true, createdAt: '2025-06-06T17:00:00Z' },
  { id: 'te-7', taskId: 'task-6', projectId: 'p-1', userId: 'u-7', date: '2025-06-06', hours: 3, description: 'Documentation Storybook composants', billable: true, createdAt: '2025-06-06T16:00:00Z' },
  { id: 'te-8', taskId: 'task-8', projectId: 'p-5', userId: 'u-3', date: '2025-06-05', hours: 3, description: 'Template rapport PDF', billable: true, createdAt: '2025-06-05T17:00:00Z' },
  { id: 'te-9', taskId: 'task-15', projectId: 'p-5', userId: 'u-6', date: '2025-06-06', hours: 5, description: 'Développement widgets KPI', billable: true, createdAt: '2025-06-06T18:00:00Z' },
  { id: 'te-10', taskId: 'task-2', projectId: 'p-1', userId: 'u-2', date: '2025-06-05', hours: 7, description: 'Tests unitaires et intégration', billable: true, createdAt: '2025-06-05T18:00:00Z' },
  { id: 'te-11', taskId: 'task-4', projectId: 'p-3', userId: 'u-4', date: '2025-06-05', hours: 8, description: 'Pipeline de migration données', billable: true, createdAt: '2025-06-05T19:00:00Z' },
  { id: 'te-12', taskId: 'task-9', projectId: 'p-3', userId: 'u-5', date: '2025-06-04', hours: 4, description: 'Configuration politiques IAM', billable: true, createdAt: '2025-06-04T17:00:00Z' },
  { id: 'te-13', taskId: 'task-11', projectId: 'p-1', userId: 'u-1', date: '2025-06-05', hours: 4, description: 'Audit Lighthouse et fixes', billable: true, createdAt: '2025-06-05T17:00:00Z' },
  { id: 'te-14', taskId: 'task-14', projectId: 'p-6', userId: 'u-1', date: '2025-05-18', hours: 8, description: 'Scan OWASP et rédaction rapport', billable: true, createdAt: '2025-05-18T18:00:00Z' },
  { id: 'te-15', taskId: 'task-1', projectId: 'p-1', userId: 'u-3', date: '2025-06-04', hours: 6, description: 'Maquettes et développement composants', billable: true, createdAt: '2025-06-04T18:00:00Z' },
  { id: 'te-16', taskId: 'task-3', projectId: 'p-2', userId: 'u-2', date: '2025-06-04', hours: 5, description: 'Cache CoreData et sync', billable: true, createdAt: '2025-06-04T17:00:00Z' },
  { id: 'te-17', taskId: 'task-15', projectId: 'p-5', userId: 'u-6', date: '2025-06-05', hours: 4, description: 'Setup charts library', billable: true, createdAt: '2025-06-05T17:00:00Z' },
  { id: 'te-18', taskId: 'task-6', projectId: 'p-1', userId: 'u-7', date: '2025-06-04', hours: 5, description: 'Cards et modals components', billable: true, createdAt: '2025-06-04T18:00:00Z' },
  { id: 'te-19', taskId: 'task-8', projectId: 'p-5', userId: 'u-3', date: '2025-06-06', hours: 3, description: 'Génération données rapport', billable: true, createdAt: '2025-06-06T15:00:00Z' },
  { id: 'te-20', taskId: 'task-9', projectId: 'p-3', userId: 'u-5', date: '2025-06-03', hours: 6, description: 'Rôles ECS et policies RDS', billable: true, createdAt: '2025-06-03T18:00:00Z' },
];

// ─── Calendar Events ────────────────────────────────────────────────────
export const mockCalendarEvents: CalendarEvent[] = [
  { id: 'ce-1', title: 'Sprint 4 Review', date: '2025-06-20', type: 'sprint', color: '#10b981', projectId: 'p-1', organizationId: 'org-1' },
  { id: 'ce-2', title: 'Alpha Release', date: '2025-06-30', type: 'milestone', color: '#10b981', projectId: 'p-1', organizationId: 'org-1' },
  { id: 'ce-3', title: 'Deadline Migration DB', date: '2025-06-12', type: 'deadline', color: '#ef4444', projectId: 'p-3', organizationId: 'org-2' },
  { id: 'ce-4', title: 'Daily Standup', date: '2025-06-09', type: 'meeting', color: '#f59e0b', organizationId: 'org-1' },
  { id: 'ce-5', title: 'Sprint 3 Review Mobile', date: '2025-06-21', type: 'sprint', color: '#f59e0b', projectId: 'p-2', organizationId: 'org-1' },
  { id: 'ce-6', title: 'Refonte UI due', date: '2025-06-15', type: 'task', color: '#06b6d4', projectId: 'p-1', organizationId: 'org-1' },
  { id: 'ce-7', title: 'Cloud Go-Live', date: '2025-07-15', type: 'milestone', color: '#06b6d4', projectId: 'p-3', organizationId: 'org-2' },
  { id: 'ce-8', title: 'Sprint Planning Q3', date: '2025-06-23', type: 'meeting', color: '#8b5cf6', organizationId: 'org-1' },
  { id: 'ce-9', title: 'Module Paiement deadline', date: '2025-07-15', type: 'deadline', color: '#ef4444', projectId: 'p-4', organizationId: 'org-3' },
  { id: 'ce-10', title: 'Beta Mobile', date: '2025-07-31', type: 'milestone', color: '#f59e0b', projectId: 'p-2', organizationId: 'org-1' },
  { id: 'ce-11', title: 'Retrospective Sprint 4', date: '2025-06-20', type: 'meeting', color: '#64748b', projectId: 'p-1', organizationId: 'org-1' },
  { id: 'ce-12', title: 'Demo Client Portal', date: '2025-06-25', type: 'meeting', color: '#8b5cf6', projectId: 'p-5', organizationId: 'org-1' },
];

// ─── Automations ────────────────────────────────────────────────────────
export const mockAutomations: Automation[] = [
  { id: 'au-1', name: 'Rappel échéance 24h', trigger: 'Deadline approaching', action: 'Send notification', enabled: true, lastRun: '2025-06-06T08:00:00Z', runCount: 124, organizationId: 'org-1' },
  { id: 'au-2', name: 'Auto-assign tâches', trigger: 'Task created', action: 'Auto-assign to project lead', enabled: true, lastRun: '2025-06-06T07:00:00Z', runCount: 89, organizationId: 'org-1' },
  { id: 'au-3', name: 'Notifier sprint start', trigger: 'Sprint started', action: 'Send notification to team', enabled: true, lastRun: '2025-06-02T09:00:00Z', runCount: 12, organizationId: 'org-1' },
  { id: 'au-4', name: 'Archiver projets terminés', trigger: 'Project completed > 30 days', action: 'Move to archive', enabled: false, lastRun: '2025-05-01T00:00:00Z', runCount: 3, organizationId: 'org-1' },
  { id: 'au-5', name: 'Rapport hebdomadaire', trigger: 'Every Monday 9:00', action: 'Generate weekly report', enabled: true, lastRun: '2025-06-02T09:00:00Z', runCount: 22, organizationId: 'org-1' },
];

// ─── Audit Logs ─────────────────────────────────────────────────────────
export const mockAuditLogs: AuditLogEntry[] = [
  { id: 'al-1', action: 'create', entityType: 'task', entityId: 'task-8', userId: 'u-3', organizationId: 'org-1', details: 'Tâche "Rapports automatisés" créée', timestamp: '2025-06-06T16:00:00Z' },
  { id: 'al-2', action: 'assign', entityType: 'task', entityId: 'task-5', userId: 'u-1', organizationId: 'org-3', details: 'Tâche "Intégration Stripe" assignée à Lucas Bernard', timestamp: '2025-06-05T17:00:00Z' },
  { id: 'al-3', action: 'move', entityType: 'task', entityId: 'task-2', userId: 'u-2', organizationId: 'org-1', details: 'Tâche "API endpoints Sprint 4" déplacée vers Done', timestamp: '2025-06-05T17:00:00Z' },
  { id: 'al-4', action: 'update', entityType: 'project', entityId: 'p-1', userId: 'u-1', organizationId: 'org-1', details: 'Projet "Refonte Platform" mis à jour (progression: 68%)', timestamp: '2025-06-06T14:00:00Z' },
  { id: 'al-5', action: 'login', entityType: 'user', entityId: 'u-1', userId: 'u-1', organizationId: 'org-1', details: 'Connexion de Marie Dupont', timestamp: '2025-06-06T07:30:00Z' },
  { id: 'al-6', action: 'permission_change', entityType: 'user', entityId: 'u-8', userId: 'u-4', organizationId: 'org-2', details: 'Rôle de David Koffi changé en Viewer', timestamp: '2025-06-05T14:00:00Z' },
  { id: 'al-7', action: 'delete', entityType: 'task', entityId: 'task-old', userId: 'u-2', organizationId: 'org-1', details: 'Tâche obsolète supprimée', timestamp: '2025-06-04T11:00:00Z' },
  { id: 'al-8', action: 'archive', entityType: 'project', entityId: 'p-6', userId: 'u-1', organizationId: 'org-1', details: 'Projet "Sécurité & Conformité" marqué comme terminé', timestamp: '2025-05-28T16:00:00Z' },
];

// ─── Organizations ──────────────────────────────────────────────────────
export const mockOrganizations: Organization[] = [
  { id: 'org-1', name: 'Global Corp France', slug: 'global-corp-france', type: 'company', color: '#3b82f6', icon: '🏢', country: 'France', memberCount: 24, projectCount: 4, isActive: true, createdAt: '2024-01-15' },
  { id: 'org-2', name: 'Global Corp RDC', slug: 'global-corp-rdc', type: 'subsidiary', color: '#f59e0b', icon: '🌍', country: 'RD Congo', memberCount: 12, projectCount: 2, isActive: true, createdAt: '2024-03-20' },
  { id: 'org-3', name: 'TechBrand', slug: 'techbrand', type: 'company', color: '#ef4444', icon: '💻', country: 'France', memberCount: 8, projectCount: 1, isActive: true, createdAt: '2024-06-10' },
  { id: 'org-4', name: 'Marketing Dept', slug: 'marketing-dept', type: 'department', color: '#8b5cf6', icon: '📣', country: 'France', memberCount: 6, projectCount: 0, isActive: true, createdAt: '2024-08-01' },
];

// ─── Helper functions ───────────────────────────────────────────────────
export function getUserName(id: string): string {
  return mockUsers.find((u) => u.id === id)?.name || 'Inconnu';
}

export function getUserInitials(id: string): string {
  const user = mockUsers.find((u) => u.id === id);
  return user ? user.name.split(' ').map((n) => n[0]).join('') : '??';
}

export function getOrganizationName(id: string): string {
  return mockUsers.find((u) => u.id === id)?.organizationName || 'Inconnu';
}

export function getProjectName(id: string): string {
  return mockProjects.find((p) => p.id === id)?.name || 'Inconnu';
}

export const taskStatusColors: Record<string, { bg: string; text: string; border: string }> = {
  todo: { bg: 'bg-slate-500/10', text: 'text-slate-600', border: 'border-slate-500/20' },
  in_progress: { bg: 'bg-amber-500/10', text: 'text-amber-600', border: 'border-amber-500/20' },
  review: { bg: 'bg-cyan-500/10', text: 'text-cyan-600', border: 'border-cyan-500/20' },
  done: { bg: 'bg-emerald-500/10', text: 'text-emerald-600', border: 'border-emerald-500/20' },
};

export const taskStatusLabels: Record<string, Record<string, string>> = {
  fr: { todo: 'À faire', in_progress: 'En cours', review: 'En revue', done: 'Terminé' },
  en: { todo: 'To Do', in_progress: 'In Progress', review: 'In Review', done: 'Done' },
};

export const taskPriorityColors: Record<string, { bg: string; text: string; border: string }> = {
  urgent: { bg: 'bg-rose-500/10', text: 'text-rose-600', border: 'border-rose-500/20' },
  high: { bg: 'bg-amber-500/10', text: 'text-amber-600', border: 'border-amber-500/20' },
  medium: { bg: 'bg-cyan-500/10', text: 'text-cyan-600', border: 'border-cyan-500/20' },
  low: { bg: 'bg-slate-500/10', text: 'text-slate-600', border: 'border-slate-500/20' },
};

export const projectStatusColors: Record<string, { bg: string; text: string; border: string }> = {
  active: { bg: 'bg-emerald-500/10', text: 'text-emerald-600', border: 'border-emerald-500/20' },
  on_hold: { bg: 'bg-amber-500/10', text: 'text-amber-600', border: 'border-amber-500/20' },
  completed: { bg: 'bg-slate-500/10', text: 'text-slate-600', border: 'border-slate-500/20' },
  archived: { bg: 'bg-slate-500/10', text: 'text-slate-500', border: 'border-slate-500/20' },
};

export const projectStatusLabels: Record<string, Record<string, string>> = {
  fr: { active: 'Actif', on_hold: 'En pause', completed: 'Terminé', archived: 'Archivé' },
  en: { active: 'Active', on_hold: 'On Hold', completed: 'Completed', archived: 'Archived' },
};

export const roleColors: Record<string, { bg: string; text: string; border: string }> = {
  super_admin: { bg: 'bg-rose-500/10', text: 'text-rose-600', border: 'border-rose-500/20' },
  org_admin: { bg: 'bg-emerald-500/10', text: 'text-emerald-600', border: 'border-emerald-500/20' },
  project_manager: { bg: 'bg-amber-500/10', text: 'text-amber-600', border: 'border-amber-500/20' },
  member: { bg: 'bg-cyan-500/10', text: 'text-cyan-600', border: 'border-cyan-500/20' },
  viewer: { bg: 'bg-slate-500/10', text: 'text-slate-600', border: 'border-slate-500/20' },
};

// ─── Teams (for teams view) ─────────────────────────────────────────────
export const mockTeams = [
  { id: 'team-1', name: 'Frontend', description: 'Équipe frontend React/Next.js', color: '#10b981', memberIds: ['u-2', 'u-3', 'u-7'], projectIds: ['p-1', 'p-5'] },
  { id: 'team-2', name: 'Backend', description: 'Équipe backend API et base de données', color: '#f59e0b', memberIds: ['u-1', 'u-2', 'u-5'], projectIds: ['p-1', 'p-3'] },
  { id: 'team-3', name: 'Mobile', description: 'Équipe mobile iOS et Android', color: '#06b6d4', memberIds: ['u-2', 'u-5'], projectIds: ['p-2'] },
  { id: 'team-4', name: 'DevOps', description: 'Équipe infrastructure et CI/CD', color: '#ef4444', memberIds: ['u-4', 'u-5'], projectIds: ['p-3'] },
  { id: 'team-5', name: 'Design', description: 'Équipe UX/UI et design system', color: '#8b5cf6', memberIds: ['u-6', 'u-7'], projectIds: ['p-1', 'p-5'] },
];

// ─── Backward-compatible aliases for existing views ──────────────────────
// These provide data for views that haven't been fully updated to PM yet

// Channels (used by messages-view)
export const mockChannels = [
  { id: 'ch-1', name: 'général', type: 'channel', description: 'Canal général de discussion', memberIds: ['u-1', 'u-2', 'u-3', 'u-4', 'u-5', 'u-6', 'u-7', 'u-8'], unreadCount: 3 },
  { id: 'ch-2', name: 'refonte-platform', type: 'channel', description: 'Discussion sur la refonte platform', memberIds: ['u-1', 'u-2', 'u-3', 'u-7'], unreadCount: 0 },
  { id: 'ch-3', name: 'app-mobile', type: 'channel', description: 'Développement app mobile v2', memberIds: ['u-2', 'u-3', 'u-5'], unreadCount: 1 },
  { id: 'ch-4', name: 'cloud-migration', type: 'channel', description: 'Migration infrastructure cloud', memberIds: ['u-1', 'u-4', 'u-5'], unreadCount: 0 },
];

// Meetings (used by meetings-view)
export const mockMeetings = [
  { id: 'mtg-1', title: 'Daily Standup', date: '2025-06-09', time: '09:00', duration: 30, status: 'scheduled', attendees: ['u-1', 'u-2', 'u-3', 'u-7'], link: 'https://meet.example.com/daily', projectId: 'p-1' },
  { id: 'mtg-2', title: 'Sprint Review S4', date: '2025-06-20', time: '14:00', duration: 60, status: 'scheduled', attendees: ['u-1', 'u-2', 'u-3', 'u-7'], link: 'https://meet.example.com/review', projectId: 'p-1' },
  { id: 'mtg-3', title: 'Sprint Planning Q3', date: '2025-06-23', time: '10:00', duration: 90, status: 'scheduled', attendees: ['u-1', 'u-2', 'u-6'], link: 'https://meet.example.com/planning', projectId: 'p-1' },
  { id: 'mtg-4', title: 'Architecture Review', date: '2025-06-06', time: '15:00', duration: 45, status: 'completed', attendees: ['u-1', 'u-4', 'u-5'], link: 'https://meet.example.com/arch', projectId: 'p-3' },
  { id: 'mtg-5', title: 'Design System Demo', date: '2025-06-06', time: '11:00', duration: 30, status: 'in_progress', attendees: ['u-6', 'u-7'], link: 'https://meet.example.com/design', projectId: 'p-1' },
];

// Activities (used by activity-view, teams-view)
export const mockActivities = [
  { id: 'act-1', type: 'task', userId: 'u-3', description: 'a complété la tâche "Maquettes Figma"', timestamp: '2025-06-06T16:00:00Z', projectId: 'p-1' },
  { id: 'act-2', type: 'comment', userId: 'u-2', description: 'a commenté "API endpoints Sprint 4"', timestamp: '2025-06-06T15:00:00Z', projectId: 'p-1' },
  { id: 'act-3', type: 'task', userId: 'u-1', description: 'a créé la tâche "Rapports automatisés"', timestamp: '2025-06-06T14:00:00Z', projectId: 'p-5' },
  { id: 'act-4', type: 'project', userId: 'u-1', description: 'a mis à jour le projet "Refonte Platform" (68%)', timestamp: '2025-06-06T13:00:00Z', projectId: 'p-1' },
  { id: 'act-5', type: 'member', userId: 'u-4', description: 'a changé le rôle de David Koffi en Viewer', timestamp: '2025-06-05T14:00:00Z', projectId: undefined },
  { id: 'act-6', type: 'task', userId: 'u-2', description: 'a déplacé "API endpoints Sprint 4" vers Terminé', timestamp: '2025-06-05T17:00:00Z', projectId: 'p-1' },
  { id: 'act-7', type: 'task', userId: 'u-1', description: 'a assigné "Intégration Stripe" à Lucas Bernard', timestamp: '2025-06-05T17:00:00Z', projectId: 'p-4' },
  { id: 'act-8', type: 'file', userId: 'u-7', description: 'a partagé "design-system-v2.fig"', timestamp: '2025-06-05T11:00:00Z', projectId: 'p-1' },
];

// CMS data stubs (used by statistics-view, dashboard-view, reports-view)
export const mockNewsletters: Array<{ id: string; tenantId: string; status: string; openRate: number; clickRate: number }> = [];
export const mockArticles: Array<{ id: string; tenantId: string; status: string }> = [];
export const mockAnnouncements: Array<{ id: string; tenantId: string; status: string }> = [];
export const mockCampaigns: Array<{ id: string; tenantId: string; status: string }> = [];

// Content status helpers (used by some views)
export const contentStatusColors: Record<string, { bg: string; text: string; border: string }> = {
  draft: { bg: 'bg-slate-500/10', text: 'text-slate-600', border: 'border-slate-500/20' },
  review: { bg: 'bg-amber-500/10', text: 'text-amber-600', border: 'border-amber-500/20' },
  published: { bg: 'bg-emerald-500/10', text: 'text-emerald-600', border: 'border-emerald-500/20' },
  archived: { bg: 'bg-slate-500/10', text: 'text-slate-500', border: 'border-slate-500/20' },
  scheduled: { bg: 'bg-cyan-500/10', text: 'text-cyan-600', border: 'border-cyan-500/20' },
};

export const contentStatusLabels: Record<string, Record<string, string>> = {
  fr: { draft: 'Brouillon', review: 'En revue', published: 'Publié', archived: 'Archivé', scheduled: 'Planifié' },
  en: { draft: 'Draft', review: 'In Review', published: 'Published', archived: 'Archived', scheduled: 'Scheduled' },
};
