
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.10.1
 * Query Engine version: 9b628578b3b7cae625e8c927178f15a170e74a9c
 */
Prisma.prismaVersion = {
  client: "6.10.1",
  engine: "9b628578b3b7cae625e8c927178f15a170e74a9c"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserProfileScalarFieldEnum = {
  neonAuthUserId: 'neonAuthUserId',
  email: 'email',
  name: 'name',
  bio: 'bio',
  role: 'role',
  status: 'status',
  avatar: 'avatar',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkspaceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  color: 'color',
  icon: 'icon',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BoardColumnScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  color: 'color',
  icon: 'icon',
  order: 'order',
  isDefault: 'isDefault',
  boardType: 'boardType',
  workspaceId: 'workspaceId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkspaceMemberScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  workspaceId: 'workspaceId',
  role: 'role',
  joinedAt: 'joinedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  workspaceId: 'workspaceId',
  invitedById: 'invitedById',
  role: 'role',
  token: 'token',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  logo: 'logo',
  sourceUrl: 'sourceUrl',
  color: 'color',
  icon: 'icon',
  status: 'status',
  dueDate: 'dueDate',
  workspaceId: 'workspaceId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OpportunityScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  organisation: 'organisation',
  status: 'status',
  dueDate: 'dueDate',
  responsableId: 'responsableId',
  workspaceId: 'workspaceId',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  tags: 'tags',
  dueDate: 'dueDate',
  projectId: 'projectId',
  assigneeId: 'assigneeId',
  creatorId: 'creatorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubtaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  completed: 'completed',
  taskId: 'taskId'
};

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  content: 'content',
  taskId: 'taskId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.ChannelScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  workspaceId: 'workspaceId',
  createdAt: 'createdAt'
};

exports.Prisma.ChannelMemberScalarFieldEnum = {
  id: 'id',
  channelId: 'channelId',
  userId: 'userId'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  content: 'content',
  channelId: 'channelId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.MeetingScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  date: 'date',
  duration: 'duration',
  status: 'status',
  link: 'link',
  projectId: 'projectId',
  createdAt: 'createdAt'
};

exports.Prisma.MeetingMemberScalarFieldEnum = {
  id: 'id',
  meetingId: 'meetingId',
  userId: 'userId'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  color: 'color',
  workspaceId: 'workspaceId',
  createdAt: 'createdAt'
};

exports.Prisma.TeamRoleScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  description: 'description',
  color: 'color',
  icon: 'icon',
  createdAt: 'createdAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.ScopeScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  name: 'name',
  description: 'description',
  type: 'type',
  icon: 'icon',
  color: 'color',
  createdAt: 'createdAt'
};

exports.Prisma.MemberScopeScalarFieldEnum = {
  id: 'id',
  memberId: 'memberId',
  scopeId: 'scopeId',
  permission: 'permission'
};

exports.Prisma.AutomationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  trigger: 'trigger',
  action: 'action',
  enabled: 'enabled',
  lastRun: 'lastRun',
  runCount: 'runCount',
  workspaceId: 'workspaceId',
  createdAt: 'createdAt'
};

exports.Prisma.TrelloIntegrationScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  trelloApiKey: 'trelloApiKey',
  trelloToken: 'trelloToken',
  boardId: 'boardId',
  boardName: 'boardName',
  listMapping: 'listMapping',
  memberMapping: 'memberMapping',
  enabled: 'enabled',
  syncDirection: 'syncDirection',
  lastSyncAt: 'lastSyncAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TrelloSyncLogScalarFieldEnum = {
  id: 'id',
  integrationId: 'integrationId',
  direction: 'direction',
  action: 'action',
  taskId: 'taskId',
  trelloCardId: 'trelloCardId',
  status: 'status',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.FileItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  size: 'size',
  url: 'url',
  projectId: 'projectId',
  workspaceId: 'workspaceId',
  uploadedBy: 'uploadedBy',
  createdAt: 'createdAt'
};

exports.Prisma.WikiPageScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  icon: 'icon',
  parentId: 'parentId',
  workspaceId: 'workspaceId',
  lastEditedBy: 'lastEditedBy',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  type: 'type',
  userId: 'userId',
  description: 'description',
  targetId: 'targetId',
  targetType: 'targetType',
  workspaceId: 'workspaceId',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};


exports.Prisma.ModelName = {
  UserProfile: 'UserProfile',
  Workspace: 'Workspace',
  BoardColumn: 'BoardColumn',
  WorkspaceMember: 'WorkspaceMember',
  Invitation: 'Invitation',
  Project: 'Project',
  Opportunity: 'Opportunity',
  Task: 'Task',
  Subtask: 'Subtask',
  Comment: 'Comment',
  Channel: 'Channel',
  ChannelMember: 'ChannelMember',
  Message: 'Message',
  Meeting: 'Meeting',
  MeetingMember: 'MeetingMember',
  Team: 'Team',
  TeamRole: 'TeamRole',
  TeamMember: 'TeamMember',
  Scope: 'Scope',
  MemberScope: 'MemberScope',
  Automation: 'Automation',
  TrelloIntegration: 'TrelloIntegration',
  TrelloSyncLog: 'TrelloSyncLog',
  FileItem: 'FileItem',
  WikiPage: 'WikiPage',
  ActivityLog: 'ActivityLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
